export const LOGIN_ACCOUNT = 'LOGIN_ACCOUNT';
export const LOGOUT_ACCOUNT = 'LOGOUT_ACCOUNT';
export const LOADING = 'LOADING';

export const WELCOME = 'WELCOME';
export const WELCOME_GET_CATEGORIES_COURSES = 'WELCOME_GET_CATEGORIES_COURSES';

export const GET_COURSE_VIDEO_LIST = 'GET_COURSE_VIDEO_LIST';
export const CHOOSE_COURSE_VIDEO = 'CHOOSE_COURSE_VIDEO';

export const GET_MY_COURSES_LIST = 'GET_MY_COURSES_LIST';



